/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;
import controller.*;


/**
 *
 * @author Thiago
 */
public class Principal extends javax.swing.JFrame {

    private AviaoController controllerA;
    private ClienteController controllerC;
    private VooController controllerV;
    private PassagemController controllerP;
    private UIController controllerUI;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AreaDeTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAviao = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuVoo = new javax.swing.JMenuItem();
        jMenuPassagem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout AreaDeTrabalhoLayout = new javax.swing.GroupLayout(AreaDeTrabalho);
        AreaDeTrabalho.setLayout(AreaDeTrabalhoLayout);
        AreaDeTrabalhoLayout.setHorizontalGroup(
            AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        AreaDeTrabalhoLayout.setVerticalGroup(
            AreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(70, 40));

        jMenu1.setText("Menus");
        jMenu1.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N

        jMenuAviao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuAviao.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jMenuAviao.setText("Menu Avião");
        jMenuAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAviaoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAviao);

        jMenuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuCliente.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jMenuCliente.setText("Menu Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCliente);

        jMenuVoo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuVoo.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jMenuVoo.setText("Menu Voo");
        jMenuVoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVooActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuVoo);

        jMenuPassagem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuPassagem.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jMenuPassagem.setText("Menu Venda de Passagem");
        jMenuPassagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPassagemActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuPassagem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaDeTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AreaDeTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAviaoActionPerformed
        abrirJanelaAviao();
    }//GEN-LAST:event_jMenuAviaoActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        abrirJanelaCliente();
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuVooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVooActionPerformed
        abrirJanelaVoo();
    }//GEN-LAST:event_jMenuVooActionPerformed

    private void jMenuPassagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPassagemActionPerformed
        abrirJanelaPassagem();
    }//GEN-LAST:event_jMenuPassagemActionPerformed

    private void abrirJanelaAviao() {
        controllerA = new AviaoController();
        controllerUI = new UIController();
        JanelaAviao ja = new JanelaAviao(controllerA);        
        AreaDeTrabalho.add(ja);
        controllerUI.centerJIF(ja, AreaDeTrabalho);
        ja.setVisible(true);
    }

    private void abrirJanelaCliente() {
        controllerC = new ClienteController();
        controllerUI = new UIController();
        JanelaCliente jc = new JanelaCliente(controllerC);
        AreaDeTrabalho.add(jc);
        controllerUI.centerJIF(jc, AreaDeTrabalho);
        jc.setVisible(true);
    }

    private void abrirJanelaVoo() {
        controllerV = new VooController();
        controllerUI = new UIController();
        JanelaVoo jv = new JanelaVoo(controllerV);
        AreaDeTrabalho.add(jv);
        controllerUI.centerJIF(jv, AreaDeTrabalho);
        jv.setVisible(true);
    }
    
    private void abrirJanelaPassagem() {
        controllerP = new PassagemController();
        controllerUI = new UIController();
        JanelaPassagem jp = new JanelaPassagem(controllerP);
        AreaDeTrabalho.add(jp);
        controllerUI.centerJIF(jp, AreaDeTrabalho);
        jp.setVisible(true);
    }

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane AreaDeTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAviao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuPassagem;
    private javax.swing.JMenuItem jMenuVoo;
    // End of variables declaration//GEN-END:variables

    
}
