package viewFomularios;

import model.Voo;
import servico.VooServico;
import controller.VooController;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.Aviao;
import model.Ponte_Aerea;
import util.DateUtil;
import servico.AviaoServico;
import javax.swing.JComboBox;

/**
 *
 * @author Thiago
 */
public class FormularioVoo extends javax.swing.JPanel {
    private AviaoServico servicoA;
    private VooServico servicoV;
    private VooController controller;

    /**
     * Creates new form FormularioVoo
     */
    public FormularioVoo(VooController control) {
        servicoA = new AviaoServico();
        servicoV = new VooServico();
        controller = control;
        initComponents();
        
//        jComboBoxAviao.setModel(new AviaoComboBoxModel(servicoA.listarAviao()));
    }
    
    public FormularioVoo() {
        servicoV = new VooServico();
        controller = new VooController();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTData = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTHora = new javax.swing.JFormattedTextField();
        jBCadastrar = new javax.swing.JButton();
        jBVoltar = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jTID = new javax.swing.JTextField();
        jLabelDataIdeal = new javax.swing.JLabel();
        jLabelDataIdeal1 = new javax.swing.JLabel();
        jComboBoxAviao = new javax.swing.JComboBox();
        jComboBoxPonte = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel1.setText("Preencha os Dados do Voo");

        jLabel2.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel2.setText("Avião:");

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel3.setText("Ponte:");

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel4.setText("Data da partida:");

        jTData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("12/12/1984"))));
        jTData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDataActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabel5.setText("Hora da Partida");

        jTHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jBCadastrar.setFont(new java.awt.Font("Lucida Console", 1, 16)); // NOI18N
        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBVoltar.setFont(new java.awt.Font("Lucida Console", 1, 16)); // NOI18N
        jBVoltar.setText("Voltar");
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jLabelID.setVisible(false);
        jTID.setVisible(false);
        jLabelID.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        jLabelID.setText("ID:");

        jLabelID.setVisible(false);
        jTID.setVisible(false);

        jLabelDataIdeal.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabelDataIdeal.setText("Formato indicado HH:MM");

        jLabelDataIdeal1.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabelDataIdeal1.setText("Formato indicado DD/MM/AAAA");

        jComboBoxAviao.setModel(new comboBoxModel.AviaoComboBoxModel());
        jComboBoxAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAviaoActionPerformed(evt);
            }
        });

        jComboBoxPonte.setModel(new comboBoxModel.PonteComboBoxModel());
        jComboBoxPonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPonteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabelID))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jBCadastrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTData, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTHora, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxAviao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxPonte, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDataIdeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDataIdeal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxAviao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxPonte, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataIdeal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataIdeal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        cadastrarVoo();
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jComboBoxAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAviaoActionPerformed
        //JOptionPane.showConfirmDialog(this, "Teste");
    }//GEN-LAST:event_jComboBoxAviaoActionPerformed

    private void jTDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDataActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        controller.voltarPrincipal();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jComboBoxPonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPonteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPonteActionPerformed
    public void cadastrarVoo() {
        //System.out.println("Selecione o Avião para realizar esse Vôo: ");
        //servicoA.mostrarAvioes();
        try {
            Aviao aviaoSelect = (Aviao)jComboBoxAviao.getSelectedItem();
            int codigo = aviaoSelect.getCodigo();
            if (servicoA.aviaoExiste(codigo)) {
                Aviao aviao = servicoA.entregaAviao(codigo);
                Date horaDoVoo = null;
                boolean dataValida;
                //do {
                    try {
                        String dataHora = jTData.getText();
                        horaDoVoo = DateUtil.stringToDateHour(dataHora+" "+jTHora.getText());
                        //dataValida = true;
                    } catch (ParseException ex) {
                        JOptionPane.showMessageDialog(this, "Data e hora no formato inválido!", "Erro: Formato inválido", JOptionPane.ERROR_MESSAGE);
                        //dataValida = false;
                    }
                //} while (!dataValida);
                //servicoV.mostrarPontes();
                
                try {
                    Ponte_Aerea ponteSelect = (Ponte_Aerea) jComboBoxPonte.getSelectedItem();
                    int opPonte = ponteSelect.getId();
                if (servicoV.ponteExiste(opPonte)) {
                    Ponte_Aerea ponteSelecionada = servicoV.entregaPonte(opPonte);
                    servicoV.addVoo(new Voo(ponteSelecionada, horaDoVoo, aviao));
                    JOptionPane.showMessageDialog(this, "Voo cadastrado com sucesso!!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Não Existe uma ponte aérea com esse código!!!\n Voo não cadastrado.", "Erro: Não Encontrado", JOptionPane.ERROR_MESSAGE);
                }
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Escreva apenas dígitos no campo Ponte", "Erro: Formato inválido", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                System.out.println("Não existe esse avião!!!\nVoo não cadastrado.");
            }

        } catch (Exception e) {
            System.out.println("Coloque apenas dígito no código de avião");
        }
    }
    
    public void carregaDados(int id, Aviao aviao, Ponte_Aerea ponte, Date dataHora){   
        this.jTID.setText(Integer.toString(id));
        this.jComboBoxAviao.setSelectedItem(aviao);
        this.jComboBoxPonte.setSelectedItem(ponte);
        this.jTData.setText(DateUtil.dateToString(dataHora));
        this.jTHora.setText(DateUtil.getHourFromDateToString(dataHora));
    }
    
    public void limparCampos() {
        jTID.setText("");
//        jComboBoxAviao.setSelectedIndex(0);
//        jComboBoxPonte.setSelectedIndex(0);
        jTData.setText("");
        jTHora.setText("");
    }

    public JButton getjBCadastrar() {
        return jBCadastrar;
    }

    public JButton getjBVoltar() {
        return jBVoltar;
    }

    public JComboBox getjComboBoxAviao() {
        return jComboBoxAviao;
    }

    public JFormattedTextField getjTData() {
        return jTData;
    }

    public JFormattedTextField getjTHora() {
        return jTHora;
    }

    public JTextField getjTID() {
        return jTID;
    }

    public JComboBox getjComboBoxPonte() {
        return jComboBoxPonte;
    }
    
    public void habilitaEdicaoFormVoo(boolean valor) {
        this.jTID.setEditable(false);
        this.jComboBoxAviao.setEditable(valor);//depois mudar para fazer a ideia que eu tenho de não permitir e abrir uma tela que selecionará a informação dos campos
        this.jComboBoxPonte.setEditable(valor);
        this.jTData.setEditable(valor);
        this.jTHora.setEditable(valor);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JComboBox jComboBoxAviao;
    private javax.swing.JComboBox jComboBoxPonte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDataIdeal;
    private javax.swing.JLabel jLabelDataIdeal1;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JFormattedTextField jTData;
    private javax.swing.JFormattedTextField jTHora;
    private javax.swing.JTextField jTID;
    // End of variables declaration//GEN-END:variables

}
